# Generated by Django 2.1.5 on 2019-02-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190206_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySub', 'verbose_name_plural': 'Subs'},
        ),
    ]
