# Generated by Django 2.1.5 on 2019-02-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='nmb',
        ),
    ]
